server:
  port: 8762

spring:
  application:
    name: demo-client
  profiles:
    active: dev



eureka:
  client:
    service-url:
      defaultZone: http://admin:fuck@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
